spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

management:
  endpoints:
    web:
      exposure:
        include: health
