package com.linkpocket.link;

enum FetchFailureReason {
    SSRF_BLOCKED,
    FETCH_TIMEOUT,
    HTTP_CLIENT_ERROR,
    HTTP_SERVER_ERROR,
    UNSUPPORTED_CONTENT_TYPE,
    CONTENT_TOO_LARGE,
    EXTRACTION_FAILED
}
